export const UPDATE_LOGIN_FIELD = "UPDATE_LOGIN_FIELD";

export const UPDATE_REGISTER_FIELD = "UPDATE_REGISTER_FIELD";
export const RESET_REGISTER_FIELDS = "RESET_REGISTER_FIELDS";

export const UPDATE_ADMIN_PROPS = "UPDATE_ADMIN_PROPS";
export const DELETE_ADMIN_PROPS = "DELETE_ADMIN_PROPS";
export const MERGE_ADMIN_PROPS = "MERGE_ADMIN_PROPS";

export const UPDATE_BOOKS_PROPS = "UPDATE_BOOKS_PROPS";
export const DELETE_BOOKS_PROPS = "DELETE_BOOKS_PROPS";
export const MERGE_BOOKS_PROPS = "MERGE_BOOKS_PROPS";


export const UPDATE_CATEGORIES_PROPS = "UPDATE_CATEGORIES_PROPS";
export const DELETE_CATEGORIES_PROPS = "DELETE_CATEGORIES_PROPS";
export const MERGE_CATEGORIES_PROPS = "MERGE_CATEGORIES_PROPS";


export const UPDATE_AUTHORS_PROPS = "UPDATE_AUTHORS_PROPS";
export const DELETE_AUTHORS_PROPS = "DELETE_AUTHORS_PROPS";
export const MERGE_AUTHORS_PROPS = "MERGE_AUTHORS_PROPS";

export const UPDATE_GENERAL_PROPS = "UPDATE_GENERAL_PROPS";
